version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install aws-sam-cli awscli --upgrade

  pre_build:
    commands:
      - echo "Cleaning up any existing stack..."
      # First attempt to delete normally
      - aws cloudformation delete-stack --stack-name hello-world-api --region eu-north-1 || true
      - echo "Waiting for 30 seconds..."
      - sleep 30
      # Then check if still exists and try with retain-resources
      - |
        if aws cloudformation describe-stacks --stack-name hello-world-api --region eu-north-1 2>/dev/null; then
          echo "Stack still exists, trying force delete with retain-resources..."
          aws cloudformation delete-stack --stack-name hello-world-api --region eu-north-1 --retain-resources "HelloWorldFunction" "ServerlessRestApi" || true
          echo "Waiting another 30 seconds..."
          sleep 30
        fi
      # Final verification
      - echo "Verifying stack is deleted..."
      - |
        if aws cloudformation describe-stacks --stack-name hello-world-api --region eu-north-1 2>/dev/null; then
          echo "Stack still exists - manual cleanup may be required"
          exit 1
        else
          echo "Stack successfully deleted"
        fi

  build:
    commands:
      - echo "Building application with SAM"
      - sam build --debug

  post_build:
    commands:
      - echo "Packaging application"
      - sam package --s3-bucket hello-lambda-deployments-binodbandara --output-template-file packaged.yaml --region eu-north-1
      - echo "Deploying application"
      - sam deploy --template-file packaged.yaml --stack-name hello-world-api --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region eu-north-1 --no-confirm-changeset --no-fail-on-empty-changeset --force-upload --debug

artifacts:
  files:
    - packaged.yaml
    - template.yaml
  discard-paths: yes
