version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Force deleting any existing stack..."
      - aws cloudformation delete-stack --stack-name hello-world-api --region eu-north-1 || true
      - echo "Waiting for stack deletion..."
      - aws cloudformation wait stack-delete-complete --stack-name hello-world-api --region eu-north-1 || true
  build:
    commands:
      - echo "Building application with SAM"
      - sam build
  post_build:
    commands:
      - echo "Packaging application with SAM"
      - sam package --s3-bucket hello-lambda-deployments-binodbandara --output-template-file packaged.yaml
      - echo "Starting deployment..."
      - >
        sam deploy 
        --template-file packaged.yaml 
        --stack-name hello-world-api 
        --capabilities CAPABILITY_IAM 
        --region eu-north-1 
        --no-confirm-changeset 
        --no-fail-on-empty-changeset

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
