version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install aws-sam-cli awscli --upgrade

  pre_build:
    commands:
      - echo "Checking stack status..."
      - |
        if aws cloudformation describe-stacks --stack-name hello-world-api --region eu-north-1 2>/dev/null; then
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name hello-world-api --region eu-north-1 --query 'Stacks[0].StackStatus' --output text)
          if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ] || [ "$STACK_STATUS" = "DELETE_FAILED" ]; then
            echo "Deleting failed stack..."
            aws cloudformation delete-stack --stack-name hello-world-api --region eu-north-1
            echo "Waiting for stack deletion..."
            aws cloudformation wait stack-delete-complete --stack-name hello-world-api --region eu-north-1
            sleep 30
          fi
        fi

  build:
    commands:
      - echo "Building application with SAM"
      - sam build --debug

  post_build:
    commands:
      - echo "Packaging application"
      - sam package --s3-bucket hello-lambda-deployments-binodbandara --output-template-file packaged.yaml --region eu-north-1
      - echo "Showing stack events before deployment..."
      - aws cloudformation describe-stack-events --stack-name hello-world-api --region eu-north-1 || true
      - echo "Deploying application"
      - |
        if ! sam deploy \
          --template-file packaged.yaml \
          --stack-name hello-world-api \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region eu-north-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --force-upload \
          --debug; then
          echo "Deployment failed. Showing stack events:"
          aws cloudformation describe-stack-events --stack-name hello-world-api --region eu-north-1
          exit 1
        fi

artifacts:
  files:
    - packaged.yaml
    - template.yaml
  discard-paths: yes
