version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade aws-sam-cli
      - pip install --upgrade awscli
  
  pre_build:
    commands:
      - echo "Setting up AWS region"
      - AWS_REGION="eu-north-1"
      - aws configure set default.region $AWS_REGION
      - echo "Cleaning up existing stack"
      - aws cloudformation delete-stack --stack-name hello-world-api || true
      - sleep 30
  
  build:
    commands:
      - echo "Building application with SAM"
      - sam build --debug
  
  post_build:
    commands:
      - echo "Packaging and deploying application"
      - |
        sam deploy \
          --template-file template.yaml \
          --stack-name hello-world-api \
          --capabilities CAPABILITY_IAM \
          --region eu-north-1 \
          --resolve-s3 \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset \
          --debug \
          --force-upload \
          --on-failure DELETE

artifacts:
  files:
    - template.yaml
    - packaged.yaml
    - .aws-sam/**/*
