version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install aws-sam-cli awscli --upgrade

  pre_build:
    commands:
      - echo "Checking and cleaning up stack status"
      - |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name hello-world-api --region eu-north-1 --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DOES_NOT_EXIST")
        if [ "$STACK_STATUS" = "ROLLBACK_FAILED" ] || [ "$STACK_STATUS" = "DELETE_FAILED" ]; then
          echo "Stack is in $STACK_STATUS state, removing stack resources..."
          aws cloudformation delete-stack --stack-name hello-world-api --region eu-north-1
          aws cloudformation wait stack-delete-complete --stack-name hello-world-api --region eu-north-1
          # Extra wait to ensure complete cleanup
          sleep 30
        fi

  build:
    commands:
      - echo "Building application with SAM"
      - sam build --debug

  post_build:
    commands:
      - echo "Packaging and deploying application"
      - |
        sam package \
          --s3-bucket hello-lambda-deployments-binodbandara \
          --output-template-file packaged.yaml \
          --region eu-north-1
      - |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name hello-world-api \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region eu-north-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --debug

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
