version: 0.2

env:
  variables:
    STACK_NAME: "hello-world-api"
    REGION: "eu-north-1"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade aws-sam-cli
      - pip install --upgrade awscli
  
  pre_build:
    commands:
      - echo "Cleaning up any existing stack"
      - aws cloudformation delete-stack --stack-name $STACK_NAME --region $REGION || true
      - sleep 60
  
  build:
    commands:
      - echo "Building SAM application"
      - sam build
      - sam validate
  
  post_build:
    commands:
      - echo "Starting deployment"
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name $STACK_NAME \
          --region $REGION \
          --capabilities CAPABILITY_IAM \
          --resolve-s3 \
          --disable-rollback \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset

artifacts:
  files:
    - template.yaml
    - .aws-sam/**/*
