AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda deployment configuration

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-api
      CodeUri: ./
      Handler: src/app.index.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
        SnsEvent:
          Type: SNS
          Properties:
            Topic: 
              Ref: SNSTopic
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref DeploymentBucket
            Events: 
              - s3:ObjectCreated:*

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hello-lambda-deployments-binodbandara

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: hello-world-topic
