AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function deployment template

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: functionfortestingplatformnex
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          abc: "ABC"  # Fixed syntax: needs space after colon
          cde: "CDE"
      Policies:
        - AWSLambdaBasicExecutionRole    
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
        # Remove or properly configure these events
        # SnsEvent:
        #   Type: SNS
        #   Properties:
        #     Topic: YOUR_SNS_TOPIC_ARN
        # S3Event:
        #   Type: S3
        #   Properties:
        #     Bucket: YOUR_BUCKET_NAME
        #     Events: 
        #       - s3:ObjectCreated:*

  # DeploymentBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: bucketfortestplatformnex
