service: hello-world-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-central-1 # Specify the AWS region

functions:
  hello-world-api:
    handler: src/app.index.handler
    memorySize: 128
    timeout: 30
    environment:
      
    events:
      - http:
          path: /hello
          method: GET
      - sns:
          arn: 
      - s3:
          bucket: hello-lambda-deployments-binodbandara
          events:
            - s3:ObjectCreated:*

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hello-lambda-deployments-binodbandara