AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function deployment template

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 3
    MemorySize: 128

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-api
      CodeUri: ./
      Handler: index.handler
      Environment:
        Variables: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello-world-api
            Method: GET

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-world-api"
